joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

position_controllers:
  ros__parameters:
    type: position_controllers/JointTrajectoryController
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3
      - link3__link4
      - link4__link5
      - link5__link6
    state_publish_rate: 50
    command_publish_rate: 30
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01
    gains:
      base_link__link1: {p: 100.0, i: 1.0, d: 1.0}
      link1__link2: {p: 100.0, i: 1.0, d: 1.0}
      link2__link3: {p: 100.0, i: 1.0, d: 1.0}
      link3__link4: {p: 100.0, i: 1.0, d: 1.0}
      link4__link5: {p: 100.0, i: 1.0, d: 1.0}
      link5__link6: {p: 100.0, i: 1.0, d: 1.0}
    stop_trajectory_duration: 0.5
    allow_partial_joints_goal: true
